config/routes.rb
Rails.application.routes.draw do
  resources :designs

end

app/models/design.rb
class Design < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/designs_controller.rb
class DesignsController < ApplicationController
  before_action :set_design, only: [:show, :edit, :update, :destroy]

  # GET /designs
  # GET /designs.json
  def index
    @designs = Design.all
  end

  # GET /designs/1
  # GET /designs/1.json
  def show
  end

  # GET /designs/new
  def new
    @design = Design.new
  end

  # GET /designs/1/edit
  def edit
  end

  # POST /designs
  # POST /designs.json
  def create
    @design = Design.new(design_params)

    respond_to do |format|
      if @design.save
        format.html { redirect_to @design, notice: 'Design was successfully created.' }
        format.json { render :show, status: :created, location: @design }
      else
        format.html { render :new }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designs/1
  # PATCH/PUT /designs/1.json
  def update
    respond_to do |format|
      if @design.update(design_params)
        format.html { redirect_to @design, notice: 'Design was successfully updated.' }
        format.json { render :show, status: :ok, location: @design }
      else
        format.html { render :edit }
        format.json { render json: @design.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designs/1
  # DELETE /designs/1.json
  def destroy
    @design.destroy
    respond_to do |format|
      format.html { redirect_to designs_url, notice: 'Design was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_design
      @design = Design.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def design_params
      params.require(:design).permit(:name, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/designs_helper.rb
module DesignsHelper
end

app/views/designs/_form.html.erb
<%= form_for(@design) do |f| %>
  <% if @design.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@design.errors.count, "error") %> prohibited this design from being saved:</h2>

      <ul>
      <% @design.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designs/edit.html.erb
<h1>Editing Design</h1>

<%= render 'form' %>

<%= link_to 'Show', @design %> |
<%= link_to 'Back', designs_path %>

app/views/designs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Designs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designs.each do |design| %>
      <tr>
        <td><%= design.name %></td>
        <td><%= design.desc %></td>
        <td><%= link_to 'Show', design %></td>
        <td><%= link_to 'Edit', edit_design_path(design) %></td>
        <td><%= link_to 'Destroy', design, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Design', new_design_path %>

app/views/designs/new.html.erb
<h1>New Design</h1>

<%= render 'form' %>

<%= link_to 'Back', designs_path %>

app/views/designs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @design.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @design.desc %>
</p>

<%= link_to 'Edit', edit_design_path(@design) %> |
<%= link_to 'Back', designs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>